<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="turtle_robot">
<xacro:property name="yaml_file" value="$(find turtle_brick)/turtle.yaml" />
<xacro:property name="props" value="${load_yaml(yaml_file)}"/>
<xacro:property name="star" value="${props['/**']}" />
<xacro:property name="ros_parameters" value="${star['ros__parameters']}" />
<xacro:property name="wheel_radius" value="${ros_parameters['wheel_radius']}" />
<xacro:property name="platform_height" value="${ros_parameters['platform_height']}" />
<xacro:property name="stem_length" value="${platform_height - 0.025 - 0.3 - 0.3 - wheel_radius*2}" />



  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.3 0.3 0.3"/>
      </geometry>
    </visual>
  </link>

  <link name="stem">
    <visual>
      <geometry>
        <cylinder length="${stem_length}" radius="0.05"/>
      </geometry>
    </visual>
  </link>

  <joint name="turn_wheel" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="base_link"/>
    <child link="stem"/>
    <origin xyz="0 0 -${0.15+stem_length/2}"/>
  </joint>

  <link name="wheel">
    <visual>
      <geometry>
        <cylinder length="0.1" radius="${wheel_radius}"/>
      </geometry>
      <origin rpy="${pi/2} 0 0 "/>
    </visual>
  </link>

  <joint name="spin_wheel" type="continuous">
    <axis xyz="0 0 1"/>
    <parent link="stem"/>
    <child link="wheel"/>
    <origin rpy="0 ${pi/2} 0" xyz="0 0 -${stem_length/2+wheel_radius}"/>
  </joint>

  <link name="tube">
    <visual>
      <geometry>
        <cylinder length="0.3" radius="0.05"/>
      </geometry>
    </visual>
  </link>

  <joint name="base_to_tube" type="fixed">
    <parent link="base_link"/>
    <child link="tube"/>
    <origin xyz="0 0 ${0.15 + 0.5*0.3}"/>
  </joint>

  <link name="platform">
    <visual>
      <geometry>
        <cylinder length="0.025" radius="0.3"/>
      </geometry>
    </visual>
  </link>

  <joint name="tilt_platform" type="revolute">    
    <parent link="tube"/>
    <child link="platform"/>
    <origin xyz="0 0 ${0.3/2 + 0.025/2}"/>
    <axis xyz="0 1 0"/>
    <limit effort="1000.0" lower="${-pi/2}" upper="${pi/2}" velocity="0.5"/>
  </joint>

</robot>